### PR TITLE
[JENKINS-51658] suggest completionGoals

### PR DESCRIPTION
**Pull request by casz**
Perhaps this should be added by the incrementals tools?

### CODE REVIEW

**Comment by jglick** [comment]
TBD what the best approach is; see discussion in [JENKINS-51658](https://issues.jenkins-ci.org/browse/JENKINS-51658). This is an interesting approach I can evaluate for addition to the parent POMs.

**Comment by casz** [comment]
This is handled really well actually as part of `[maven-release-plugin] prepare for next development iteration` commit
see https://github.com/jenkinsci/kotlin-v1-stdlib-jdk8-plugin/commit/afc674665f767aeec664536c8b6fb64961fda48f

**Comment by oleg-nenashev** [comment]
Sorry, I should have read the comment :(
If it works OOTB, +1 for including it into Plugin POM and Jenkins POM

**Comment by jglick** [comment]
Agreed, thanks for tip, I will try to pick this up.

**Comment by casz** [comment]
You should thank @ndeloof for pointing it out over at https://github.com/jenkinsci/configuration-as-code-plugin/pull/341#issuecomment-403466933

**Comment by jglick** [comment]
Superseded by https://github.com/jenkinsci/plugin-pom/pull/117.

**Comment by jglick** [comment]
See https://github.com/jenkinsci/incrementals-tools/blob/master/README.md#running-maven-releases for updated docs.

**Pull request closed without merging**
