### PR TITLE
[JENKINS-51658] add NOOP to reincrementalify

### PR DESCRIPTION
**Pull request by casz**
To avoid breaking POM with `reincrementalify` if POM does not contain `revison` or `changelist` a change that https://github.com/jenkinsci/plugin-pom/pull/117 depends on

### CODE REVIEW

**Comment by casz** [comment]
Seems reasonable

**Comment by casz** [comment]
```
[ERROR] Failed to execute goal io.jenkins.tools.incrementals:incrementals-maven-plugin:1.0-beta-4-SNAPSHOT:reincrementalify (default-cli) on project cloudbees-bitbucket-branch-source: Cannot use reincrementalify before enabling incrementals: Cannot use reincrementalify before enabling incrementals:
[ERROR] Please use 'incrementals:incrementalify' to enable incrementals
```

**Comment by casz** [comment]
@jglick haven't tested a pom with multiple modules.

**Comment by casz** [comment]
Works fine in multi module 👍

**Comment by jglick** [comment]
AFAICT running the goal twice on an incrementalified project was already a no-op, so this is safe as it should only affect projects which are not set up for Incrementals at all.

**Pull request merged**
